accounts/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('login/', views.loginUser, name='login'),
    path('logout/', views.logoutUser, name='logout'),
    path('register/', views.registerUser, name='register'),
    
    path('view/', views.view_account, name="view-account"),
    path('edit/<str:pk>', views.AccountUpdateView.as_view(), name="edit-account"),

    path('customer/new/', views.customer_new, name="customer-new"),

    #path('contact/', views.contact_us, name="contact-us"),
    path("contact", views.contact, name="contact"),

    path('subscription/new/', views.subscription_new, name="subscription-new"),
    path('subscription/success/', views.subscription_success, name="subscription-success"),
    path('edit-subscription/<str:pk>', views.edit_subscription, name="renew-subscription"),
    path('subscription/cancel/', views.cancel_subscription, name="cancel-subscription")
]

clubApp/urls.py
from django.urls import path
from . import views
from .views import IndexView

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('club/videos/', views.viewVideoList, name='videolist'),
    path('club/video/<int:pk>', views.videoView, name='video'),
    path('club/stats/<int:pk>', views.StatisticsView.as_view(), name='stats'), 

    path('ajax/update_video_watch_time/', views.update_video_watch_time, name='updateWatchTime'),
    path('ajax/update_video_views/', views.update_video_views, name='updateViews'),
    path('ajax/update_video_rating/', views.update_video_rating, name='updateRating'),
    path('ajax/get_video_rating/<int:pk>', views.get_video_rating, name='getRating')
]

clubExProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from clubApp.views import IndexView


# url patterns
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('clubApp.urls')),
    path('accounts/', include('accounts.urls')),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
import uuid
from django.db.models.deletion import CASCADE
import datetime
from datetime import date
from django.urls import reverse

# Create your models here.


class Customer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True, blank=True, related_name='customer')
    username = models.CharField(max_length=200, blank=True, null=True)
    first_name = models.CharField(max_length=50, default='', null=True, blank=True)
    last_name = models.CharField(max_length=50, default='', null=True, blank=True)
    address_1 = models.CharField(max_length=50, default='', null=True, blank=True)
    address_2 = models.CharField(max_length=50, null=True, blank=True)
    city = models.CharField(max_length=50, default='', null=True, blank=True)
    country = models.CharField(max_length=50, null=True, blank=True)
    zip_address = models.CharField(max_length=10, null=True, blank=True)
    email = models.EmailField(max_length=100, default='', null=True, blank=True)
    phone = models.CharField(max_length=20, default='', null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=True)

    def __str__(self):
        return (self.username)

    def get_absolute_url(self):
        return reverse("view-account")

# Subscription Choices
SUBSCRIPTION_CHOICES = (
    ('ANNUAL_GYM' , 'Annual Gym Membership',),
    ('MONTHLY_GYM' , 'Monthly Gym Membership',),
    ('ANNUAL_ONLINE' , 'Annual Online Membership',),
    ('MONTHLY_ONLINE' , 'Monthly Online Membership',),
)


class Subscription(models.Model):
    subscription_id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)
    subscription_choice = models.CharField(max_length=30, choices=SUBSCRIPTION_CHOICES,default='0')
    renewal_date = models.DateField(default=datetime.date.today)
    start_date = models.DateField(default=datetime.date.today)
    customer_id = models.ForeignKey(Customer, on_delete=models.CASCADE)
    created_date = models.DateField(default=datetime.date.today)

    @property
    def is_expired(self):
        return date.today() > self.renewal_date

    @property
    def expires_today(self):
        return date.today() == self.renewal_date

    def __str__(self):
        return str(self.subscription_choice)


class Payment(models.Model):
    customer_id = models.ForeignKey(Customer, on_delete=models.CASCADE)
    card_holder = models.CharField(max_length=100)
    number = models.CharField(max_length=100)
    expiry = models.DateField(default=datetime.date.today)
    cvv = models.CharField(max_length=100)
    payment_amount = models.DecimalField(max_digits=6, decimal_places=2, default=0)
    created_date = models.DateField(default=datetime.date.today)

    def __str__(self):
        return str(self.card_holder)

accounts/views.py
from datetime import date, datetime, timedelta
from django.urls import reverse_lazy
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .forms import ContactForm
from django.core.mail import send_mail, BadHeaderError
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.contrib.auth.models import User, Group
from .models import Customer, Subscription, Payment
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from .forms import CustomUserCreationForm, CustomerForm, SubscriptionForm
from .utils import has_current_subscription, renew_subscription, save_subscription

from django.views.generic.edit import UpdateView, CreateView, DeleteView
from django.utils.decorators import method_decorator


# Create your views here.
def loginUser(request):
    page = 'login'

    errors = {}

    if request.user.is_authenticated:
        return redirect('index')

    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']

        user = authenticate(request, username=username, password=password)
        
        if user is not None:
            if has_current_subscription(user):
                login(request, user)
                return redirect('index')
            else:
                login(request, user)
                return redirect('subscription-new')
        else:
            errors = {'errors':'Username or Password is incorrect'}
    return render(request, 'login.html', errors)


@login_required(login_url='login')
def logoutUser(request):
    logout(request)
    messages.info(request, 'User was logged out')
    return redirect('login')


def registerUser(request):
    page = 'register'
    form = CustomUserCreationForm()

    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            print('form is valid')
            user = form.save(commit=False)
            print(user)
            user.username = user.username.lower()
            user.save()

            messages.success(request, 'User account was created!')

            login(request, user)
            return redirect('customer-new')

    context = {'page': page, 'form': form}
    return render(request, 'signup.html', context)



@login_required(login_url='login')
def view_account(request):
    try:
        customer = Customer.objects.get(user=request.user)
        subscriptions = Subscription.objects.filter(customer_id=customer).order_by('-renewal_date')
        context = {'logged_user': customer, 'subscriptions': subscriptions}
    except:
        admin = User.objects.get(username=request.user)
        context = {'logged_user': admin}
    return render(request, 'account.html', context)


@login_required(login_url='login')
def contact_us(request):
    try:
        customer = Customer.objects.get(user=request.user)
        context = {'logged_user': customer}
    except:
        admin = User.objects.get(username=request.user)
        context = {'logged_user': admin}
    return render(request, 'contact-us.html', context)


def contact(request):
	if request.method == 'POST':
		form = ContactForm(request.POST)
		if form.is_valid():
			subject = "Website Inquiry" 
			body = {
			'first_name': form.cleaned_data['first_name'], 
			'last_name': form.cleaned_data['last_name'], 
			'email': form.cleaned_data['email_address'], 
			'message':form.cleaned_data['message'], 
			}
			message = "\n".join(body.values())

			try:
				send_mail(subject, message, 'admin@example.com', ['admin@example.com']) 
			except BadHeaderError:
				return HttpResponse('Invalid header found.')
			return redirect ('index')
      
	form = ContactForm()
	return render(request, "contact.html", {'form':form})




@login_required(login_url='login')
def editAccount(request):
    customer = Customer.objects.get(user=request.user)
    form = CustomerForm(instance=customer)

    if request.method == 'POST':
        form = Customer(request.POST, request.FILES, instance=customer)
        if form.is_valid():
            form.save()

            return redirect('account')

    context = {'form': form}
    return render(request, 'account.html', context)


class AccountUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    form_class = CustomerForm
    
    model = Customer

    template_name = 'edit-account.html'

    context_object_name = 'account'

    def test_func(self):
        obj = self.get_object()
        return obj.user == self.request.user

    def form_valid(self, form):
        user = self.request.user
        data = self.request.POST
        # check user hasn't been tampered
        if data.get('user') == str(user.id):
            return super().form_valid(form)
        else:
            form.errors['Input is invalid: '] = "You can not modify your username!"
            return self.form_invalid(form)


@login_required(login_url='login')
def customer_new(request):
    customer = Customer.objects.get(user=request.user)
    form = CustomerForm(instance=customer)

    if request.method == 'POST':
        form = CustomerForm(request.POST)
        if form.is_valid():
            customer.phone = form.cleaned_data['phone']
            customer.email = form.cleaned_data['email']
            customer.address_1 = form.cleaned_data['address_1']
            customer.address_2 = form.cleaned_data['address_2']
            customer.city = form.cleaned_data['city']
            customer.zip_address = form.cleaned_data['zip_address']
            customer.country = form.cleaned_data['country']

            try: 
                customer.save()
                return redirect('subscription-new')
            except: 
                return redirect(request, 'customer-new.html', {'form':form})

    return render(request, 'customer-new.html', {'form': form})


@login_required(login_url='login')
def subscription_new(request):

    #subscription_form = SubscriptionForm
    todaysDate = date.today().strftime('%Y-%m-%d')
    endDate = date.today().strftime('%Y-%m')

    print(endDate)

    context = {'start_date' : todaysDate, 'end_date': endDate}
    cost = ''
    sub_type = ''
    renewal = date.today()

    ## TODO: Add Server Side Form Validation 

    if request.method == 'POST':
        did_it_save = save_subscription(request)
        if did_it_save and request.POST['expiry-date'] >= endDate:
            return redirect('subscription-success')
        else:
            formIncomplete = "Payment Details were either entered incorrectly or are invalid please try again"
            context = {'FormIncomplete': formIncomplete, 'start_date' : todaysDate, 'end_date': endDate}
            return render(request, 'subscription-new.html', context)
    else:
        return render(request, 'subscription-new.html', context)



@login_required(login_url='login')
def subscription_success(request):
    customer = Customer.objects.get(user=request.user)
    subscriptions = Subscription.objects.filter(customer_id=customer.id, start_date=date.today())
    subscription = Subscription.objects.get(subscription_id=subscriptions[0].subscription_id)

    form = SubscriptionForm(instance=subscription)
    return render(request, 'subscription-success.html', {'form': form, 'customer': customer})



def edit_subscription(request, pk):
    try:
        subscription_model = Subscription.objects.get(customer_id = pk)
    except:
        return redirect('subscription-new')
    try:
        customer = Customer.objects.get(id = pk)
        payment_model = Payment.objects.get(customer_id = customer)
    except:
        return redirect('subscription-new')
    
    todaysDate = date.today().strftime('%Y-%m-%d')
    endDate = date.today().strftime('%Y-%m')
    cost = 200
    if request.method == 'POST':
        #print(request.POST)
        if request.POST['expiry-date'] >= endDate:
            did_it_save = renew_subscription(request, subscription_model, payment_model)
            if did_it_save:
                return redirect('subscription-success')
            else:
                formIncomplete = "Payment Details were either entered incorrectly or are invalid please try again"
                context = {'FormIncomplete': formIncomplete, 'start_date' : todaysDate, 'end_date': endDate, 'cost': cost}
                return render(request, 'subscription-new.html', context)
        else:
            formIncomplete = "Payment Details were either entered incorrectly or are invalid please try again"
            context = {'FormIncomplete': formIncomplete, 'start_date' : todaysDate, 'end_date': endDate, 'cost': cost}
            return render(request, 'subscription-new.html', context)

    context = { 'start_date' : todaysDate, 'end_date': endDate, 'cost': cost}
    return render(request, 'subscription-new.html', context)


def cancel_subscription(request):
    try:
        customer = Customer.objects.get(user=request.user)
        subscription = Subscription.objects.filter(customer_id=customer.id, renewal_date__gt=datetime.today())
        subscription_update = Subscription.objects.get(subscription_id=subscription[0].subscription_id)
        subscription_update.renewal_date = date.today()
        subscription_update.save()
    except:
        return redirect('view-account')
    return redirect('view-account')

templates/account.html
{% extends 'base.html' %}
{% load app_tags %}
{% block content %}
<div class="container">
    

    <p class="row">
       
        <h3>Account Information</h3>
        <table>
            <thead>
            <tr>
                <th>Field</th>
                <th>Data</th>
            </tr>
            </thead>

            <tbody>
            <tr>
                <td><strong>Username</strong></td>
                <td>{{logged_user.username}}</td>
            </tr>
            <tr>
                <td><strong>First Name</strong></td>
                <td>{{logged_user.first_name}}</td>
            </tr>
            <tr>
                <td><strong>Last Name</strong></td>
                <td>{{logged_user.last_name}}</td>
            </tr>
            <tr>
                <td><strong>Phone</strong></td>
                <td>{{logged_user.phone}}</td>
            </tr>
            <tr>
                <td><strong>Email</strong></td>
                <td>{{logged_user.email}}</td>
            </tr> 
            <tr>
                <td><strong>Address</strong></td>
                <td>
                {{logged_user.address_1}}<br>
                {% if logged_user.address_2 %}
                    {{logged_user.address_2}}<br>
                {% endif %}
                {{logged_user.city}} {{logged_user.zip_address}}<br>
                {{logged_user.country}}
                </td>
            </tr>                 
            </tbody>
        </table>
        <p></p>
        <div>
            <a class="waves-effect waves-light blue btn" href="{%url "edit-account" logged_user.id %}">Update Account</a>
        </div> 

        <br><br>

        {% is_user_customer user as is_customer%}
        {% now "M, j, Y" as date %}

        {% if is_customer %}
            <h4>Subscriptions</h4>
            <p>Your current and previous subscription history is located here.</p>

            {% count_valid_user_subscriptions user as valid_subscription %}
            <div class="row">
                <div class="col s12 m12">
                {% if valid_subscription == 0 %}
                    <div class="card red lighten-5">
                {% else %}
                    <div class="card green lighten-5">
                {% endif %}
                    <div class="card-content black-text">
                    <span class="card-title black-text">Current Subscription</span>
                    {% if valid_subscription == 0 %}
                        <p class="red-text">You do not have a valid subscription.</p>
                    </div>
                    <div class="card-action">
                        <a class="waves-effect waves-light blue btn" href="{%url "subscription-new" %}">Purchase Subscription</a>
                    </div>
                    {% else %}
                    {% get_valid_user_subscription user as valid_subscription %}
                        <table>
                            <thead>
                            <tr>
                                <th>Start Date</th>
                                <th>Subscription Type</th>
                                <th>Expiry Date</th>
                            </tr>
                            </thead>
                    
                            <tbody>
                                <tr>
                                    <td>{{valid_subscription.start_date}}</td>
                                    <td>{{valid_subscription.get_subscription_choice_display}}</td>
                                    <td>{{valid_subscription.renewal_date}}</td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                    {% if date == valid_subscription.renewal_date|date:"M, j, Y" %}
                        <p class="center-align red-text"><strong>Your Subscription ends today.  Purchase another subscription for continued access</strong></p>
                    {% endif %}
                    <div class="card-action">
                        {% if date == valid_subscription.renewal_date|date:"M, j, Y" %}
                            <a class="waves-effect waves-light blue btn" href="{%url "subscription-new" %}">Purchase Subscription</a>
                        {% else %}
                            <a class="waves-effect waves-light red btn modal-trigger" data-target="modal1">Cancel Subscription</a>
                        {% endif %}
                    </div>
                    {% endif %}

                </div>
                </div>
            </div>

            <div class="row">
                <div class="col s12 m12">
                <div class="card blue lighten-5">
                    <div class="card-content black-text">
                    <span class="card-title black-text">Subscription History</span>
                    <p>Your subscription history ordered by the expiry date is located here.</p>
                    <table>
                        <thead>
                        <tr>
                            <th>Start Date</th>
                            <th>Subscription Type</th>
                            <th>Expiry Date</th>
                            <th></th>
                        </tr>
                        </thead>
                
                        <tbody>
                            {% for field in subscriptions %}
                            <tr>
                                <td>{{field.start_date}}</td>
                                <td>{{field.get_subscription_choice_display}}</td>
                                <td>{{field.renewal_date}}</td>
                                <td>
                                {% if field.is_expired %}
                                    <p>Subscription Expired</p>
                                {% else %}
                                    {% if field.expires_today %}
                                        <p class="red-text text-darken-4"><strong>Expires Today</strong></p>
                                    {% else %}
                                        <p class="green-text text-darken-4"><strong>Current</strong></p>
                                    {% endif %}  
                                {% endif %}
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                    </div>
                </div>
            </div>
        {% endif %}
    </p>
   
</div>
<br>

<!-- Subscription Confirmation Modal -->
<div id="modal1" class="modal">
<div class="modal-content">
    <h4>Cancel Subscription</h4>
    <p>
        Are you sure you want to cancel your current subscription?<br>
        If you cancel, you will no longer be able to access all our great online content!
    </p>
</div>
<div class="modal-footer">
    <a href="#!" class="modal-close waves-light green btn">Stay Subscribed</a>
    <a href="{% url 'cancel-subscription' %}" class="modal-close waves-light red btn">Cancel Subscription</a>
</div>
</div>

<script>

document.addEventListener('DOMContentLoaded', function() {
    var elems = document.querySelectorAll('.modal');
    var instances = M.Modal.init(elems, {});
});

</script>



{% endblock content %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>ClubEX - Online Gym</title>

    <link
      href="https://fonts.googleapis.com/icon?family=Material+Icons"
      rel="stylesheet"
    />
    <!--Import materialize.css-->
    <link
      type="text/css"
      rel="stylesheet"
      href="{% static 'css/materialize.min.css' %}"
      media="screen,projection"
    />

    <link
      href="{% static 'css/style.css' %}"
      type="text/css"
      rel="stylesheet"
      media="screen,projection"
    />
    {% block styles %} {% endblock styles %}
  </head>
  <body>
    <nav class="white" role="navigation">
      <div class="nav-wrapper container">
        <a id="logo-container" href='{%url "index"%}' class="brand-logo">
          <img
            width="80%"
            class="responsive-img"
            src="{% static 'img/logo_blue.png' %}"
          />
        </a>
        <ul class="right hide-on-med-and-down">
          <li><a href="{%url 'index'%}">Home</a></li>

          {% if user.is_authenticated %}
            <li><a href='{%url "stats" user.id %}'>Statistics</a></li>
            <li><a href='{%url "videolist"%}'>Video List</a></li>
            <li><a href='{%url "view-account"%}'>Account</a></li>
            <li><a href='{%url "contact"%}'>Contact Us</a></li>
            <li><a href='{%url "logout"%}'>Logout</a></li>
          {% else %}
            <li><a href='{%url "login"%}'>Sign In</a></li>
            <li><a href='{%url "register"%}'>Sign Up</a></li>
          {% endif %}
        </ul>

        <ul id="nav-mobile" class="sidenav">
          <li><a href='{%url "index"%}'>Home</a></li>

          {% if user.is_authenticated %}
            <li><a href='{%url "stats" user.id %}'>Statistics</a></li>
            <li><a href='{%url "videolist"%}'>Video List</a></li>
            <li><a href='{%url "view-account"%}'>Account</a></li>
            <li><a href='{%url "contact"%}'>Contact Us</a></li>
            <li><a href='{%url "logout"%}'>Logout</a></li>
          {% else %}
            <li><a href='{%url "login"%}'>Sign In</a></li>
            <li><a href='{%url "register"%}'>Sign Up</a></li>
          {% endif %}
        </ul>
        <a href="#" data-target="nav-mobile" class="sidenav-trigger blue-text"
          ><i class="material-icons">menu</i></a
        >
      </div>
    </nav>

    {% block content %} {% endblock content %}

    <footer class="page-footer blue">
      {% block footer_content %} {% endblock footer_content %}
      <div class="footer-copyright">
        <div class="container">
          Made by <span class="brown-text text-lighten-3">Edible Coders</span>
        </div>
      </div>
    </footer>

    <script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
    <script src="{% static 'js/materialize.min.js' %}"></script>
    <script src="{% static 'js/splide.min.js' %}"></script>
    <script src="{% static 'js/init.js' %}"></script>
    {% block scripts %} {% endblock scripts %}
  </body>
</html>

templates/contact.html
{% extends 'base.html' %} 
{% block content %}

<!--Contact form-->
<div style="margin:80px">
    <h1>Contact Us</h1>
    <h4>Contact us directly if you have any questions</h4>
    <p>
        Please write your name, email address and a message below if you have any questions.
        One of our staff members will be happy to contact you directly and answer your questions as soon as possible. 
    </p>
    <form method="post">
    {% csrf_token %}
        {{form.as_p}}
        <button type="submit">Submit</button>
    </form>
</div>

{% endblock content %}

templates/customer-new.html
{% extends 'base.html' %} {% block content %}
<div class="container">

    <form class="col s12" method='POST' novalidate>
    {% csrf_token %}
        <h4 class="blue-text">Complete Signup</h4>
        <br>

        <div class="row">
          <h5 class="blue-text">Personal Information</h5>
          <div class="input-field col s12 l6">
              {{form.first_name}}
              <label for="{{ form.first_name.id_for_label }}" class="blue-text">{{form.first_name.label}}</label>
              <span style="color: red; font-weight: 600;">{{form.first_name.errors}}</span>
              <span class="helper-text">{{form.first_name.help_text}}</span>
          </div>

          <div class="input-field col s12 l6">
              {{form.last_name}}
              <label for="{{ form.last_name.id_for_label }}" class="blue-text">{{form.last_name.label}}</label>
              <span style="color: red; font-weight: 600;">{{form.last_name.errors}}</span>
              <span class="helper-text">{{form.last_name.help_text}}</span>
          </div>

          <div class="input-field col s12">
              <label for="{{ form.email.id_for_label }}" class="blue-text">{{form.email.label}}</label>
            {{form.email}}
              <span class="helper-text">{{form.email.help_text}}</span>
              <span style="color: red; font-weight: 600;">{{form.email.errors}}</span>
          </div>

          <div class="input-field col s12 l6">
              {{form.phone}}
              <label for="{{ form.phone.id_for_label }}" class="blue-text">{{form.phone.label}}</label>
              <span style="color: red; font-weight: 600;">{{form.phone.errors}}</span>
              <span class="helper-text">{{form.phone.help_text}}</span>
          </div>     

        </div>

        <br>

        <div class="row">
          <h5 class="blue-text">Address</h5>
          <div class="input-field col s12">
              <label for="{{form.address_1.id_for_label}}" class="blue-text">{{form.address_1.label}}</label>
              {{form.address_1}}
              <span class="helper-text">{{form.address_1.help_text}}</span>
              <span style="color: red; font-weight: 600;">{{form.address_1.errors}}</span>
          </div>

          <div class="input-field col s12">
              <label for="{{form.address_2.id_for_label}}" class="blue-text">{{form.address_2.label}}</label>
              {{form.address_2}}
              <span class="helper-text">{{form.address_2.help_text}}</span>
              <span style="color: red; font-weight: 600;">{{form.address_2.errors}}</span>
          </div>

          <div class="input-field col s12 l6">
              <label for="{{form.city.id_for_label}}" class="blue-text">{{form.city.label}}</label>
              {{form.city}}
              <span class="helper-text">{{form.city.help_text}}</span>
              <span style="color: red; font-weight: 600;">{{form.city.errors}}</span>
          </div>

          <div class="input-field col s12 l6">
              <label for="{{form.zip_address.id_for_label}}" class="blue-text">{{form.zip_address.label}}</label>
              {{form.zip_address}}
              <span class="helper-text">{{form.zip_address.help_text}}</span>
              <span style="color: red; font-weight: 600;">{{form.zip_address.errors}}</span>
          </div>

          <div class="input-field col s12 l6">
              <label for="{{form.country.id_for_label}}" class="blue-text">{{form.country.label}}</label>
              {{form.country}}
              <span class="helper-text">{{form.country.help_text}}</span>
              <span style="color: red; font-weight: 600;">{{form.country.errors}}</span>
          </div>
        </div>
      <br>

      <div class="row">
        <div class="col s12">
          <button type="submit" class="waves-effect waves-light blue btn"  value="Continue">
            Continue
          </button>
        </div>
      </div>

      <br>

    </form>
  </div>
</div>
{% endblock content %}

templates/edit-account.html
{% extends 'base.html' %} 

{% block content %}
<div class="container">
    <h1>Edit Account Information</h1>
    <form class="col s12" method='post'>
        {% csrf_token %}
        {% if form.errors %}
         <h5 class="">Form Errors</h5>
            {{form.errors}}
        {% endif %}
        <div class="input-field col s12">
            {{form.user}}
        </div>
        {% for field in form %}
            <div class="input-field col s12">
                {% if field != form.user %}
                    {{field.label}}
                    {{field}}
                {% endif %}
            </div>
        {% endfor %}
        <div class="row">
            <div class="col s12 center-align">
                <button type="submit" class="waves-effect waves-light blue btn" style="max-width: 40%; width: 100%;" value="save">Save</button>
                <a class="waves-effect waves-light grey darken-3 btn" style="max-width: 40%; width: 100%;" href="{% url 'view-account' %}">Back</a>
            </div>
        </div>
    </form>
</div>
{% endblock content %}

templates/login.html
{% extends 'base.html' %} 

{% block content %}
<div class="container">
  <div class="row">
    <div class="col s12"><h2 class="blue-text">Login</h2></div>
  </div>
  <div class="row">

    <form class="col s12" method='POST'>
    {% csrf_token %}
      <div class="row">

        <div class="input-field col s12">
          <input id="username" type="text" name="username" class="validate blue-text" />
          <label for="username">Username</label>
          <!-- <span
            class="helper-text"
            data-error="Please enter a valid username"
            data-success=""
          ></span> -->
        </div>

        <div class="input-field col s12">
          <input id="password" type="password" name="password" class="blue-text" />
          <label for="password">Password</label>
        </div>
      </div>

      <div class="row">
            <p class="helper-text red-text">{{errors}}</p>
      </div>


      <div class="row">
        <div class="col s12">
          <button type="submit" class="waves-effect waves-light blue btn">
            Submit
          </button>
        </div>
      </div>

    </form>
  </div>
</div>
{% endblock content %}